name: 'Fetch Secrets from Azure Key Vault'
description: 'Fetches secrets from Azure Key Vault and sets them as outputs'
inputs:
  azure_credentials:
    description: 'Azure credentials JSON'
    required: true
  key_vault_name:
    description: 'The name of the Azure Key Vault'
    required: true
  secret_names:
    description: 'Comma-separated list of secret names to fetch'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ inputs.azure_credentials }}

    - name: Fetch Secrets and Set Outputs
      shell: pwsh
      run: |
        $secrets = "${{ inputs.secret_names }}".Split(',')
        foreach ($secret_name in $secrets) {
          $secret_value = az keyvault secret show --name $secret_name --vault-name "${{ inputs.key_vault_name }}" --query value -o tsv
          # Use environment files to set outputs in PowerShell
          "$secret_name=$secret_value" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        }