name: Deploy ADF Pipeline

on:
  workflow_dispatch:


env:
  DEV_RESOURCE_GROUP: 'ADF_POC_2'
  DEV_ADF_NAME: 'adf-sendfile-poc'
  OUTPUT_PATH: './ArmTemplateOutput'

jobs:
  build-adf:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
    - uses: actions/checkout@v2

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Extract Subscription ID from Azure Credentials
      shell: pwsh
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      run: |
        $creds = $env:AZURE_CREDENTIALS | ConvertFrom-Json
        $subscriptionId = $creds.subscriptionId
        echo "SUBSCRIPTION_ID=$subscriptionId" >> $GITHUB_ENV

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install npm dependencies
      run: npm install

    - name: Build ADF files
      run: |
        npm run build export ./ /subscriptions/${{ env.SUBSCRIPTION_ID }}/resourceGroups/${{ env.DEV_RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ env.DEV_ADF_NAME }} ${{ env.OUTPUT_PATH }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: ${{ env.OUTPUT_PATH }}


 