name: Deploy ADF Pipeline

on:
  workflow_dispatch:


env:
  ARM_TEMPLATE_PATH: './templates/ADF_CNP_ReDesign_MainPL/ADF_CNP_ReDesign_MainPL.json'
  DEV_RESOURCE_GROUP: 'ADF_POC_2'
  DEV_ADF_NAME: 'adf-sendfile-poc'
  OUTPUT_PATH: './ArmTemplateOutput'

jobs:
  build-adf:
    runs-on: ubuntu-latest
    environment: DEV
    defaults:
      run:
        working-directory: ./

    steps:
    - uses: actions/checkout@v2

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
    
    - name: Buiild ADF files
      run: |
        npm run build export ./ /subscriptions/a4b8e661-a729-4d5d-a473-07e2384b262d/resourceGroups/${{ env.DEV_RESOURCE_GROUP }}/providers/Microsoft.DataFactory/factories/${{ env.DEV_ADF_NAME }} ${{ env.OUTPUT_PATH }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: ${{ env.OUTPUT_PATH }}/


  deploy-qa:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/temporary_disabled'
    environment: QA

    steps:
    - uses: actions/checkout@v2

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    #TBD

 